config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  post 'home/search', to: 'home#search'
  devise_for :users
  resources :users, :only => [:index, :show]
  resources :profiles, only: [:new, :create, :show, :edit, :update]

  resources :artists, only: [:index]

  get 'about' => 'about#index'

  patch 'listings/:listing_id/biddings/:id/approve' => 'biddings#approve'
  patch 'listings/:listing_id/biddings/:id/deny' => 'biddings#deny'

  resources :listings do
    resources :biddings
  end

  resources :charges, only: [:new, :create]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/profile.rb
class Profile < ApplicationRecord
  include Rails.application.routes.url_helpers
  before_save { |profile| profile.name = profile.name.downcase }
  before_save { |profile| profile.location = profile.location.downcase }

  belongs_to :user

  has_one_attached :avatar

  # has_one :email, -> (email) { where(user_id: ) }

  has_many :listings, through: :user

  validates :name, :nickname, :bio, :location, presence: true

  scope :artists, -> { where(is_artist: true) }
  scope :search,    ->  (name){ where("name LIKE ?", "%#{name}%") }


  def as_json(options={})
    {
      user_id:        user_id,
      name:           name,
      nickname:       bio,
      location:       location,
      bio:            bio,
      url:            "/artists/#{id}",
      avatar:         rails_blob_url(self.avatar)
    }

  end

  def email
    user = User.find(self.user_id)

    return user.email
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def index
    if params[:artists]
      @profiles = Profile.artists
    else
      @profiles = Profile.all
    end
  end

  def new
    @profile = Profile.new
  end

  def create
    @profile = Profile.find_or_initialize_by(user_id: current_user.id)
    @profile.assign_attributes(profile_params)
    @profile.save
    redirect_to root_path
  end

  def edit
    @profile = current_user.profile
  end

  def update
    @profile = current_user.profile
    if @profile.update(profile_params)
      redirect_to profile_path(@profile), notice: "Profile updated"
    else
      redirect_to edit_profile_path(@profile), alert: @profile.errors.full_messages.to_sentence
    end
  end

  def show
    @profile = Profile.find(params[:id])
  end

  private


  def profile_params
    params.require(:profile).permit(:name, :nickname, :bio, :location, :is_artist, :avatar)
  end
end

app/views/profiles/_form.html.erb
<%= form_for(@profile) do |form|%>
<div id="test2">
  <div id="beautify">
    <% if current_user.profile %>
      <h1>Edit Profile</h1>
    <% else %>
      <h1>Create Profile</h1>
    <% end %>
    <br><br>
    <div class="form-group row">
      <%=form.label :name, class: "col-sm-4 col-form-label" %>
      <%=form.text_field :name, class: "col-sm-6" %>
    </div><br>
    <div class="form-group row">
      <%=form.label :nickname, class: "col-sm-4 col-form-label" %>
      <%=form.text_field :nickname, class: "col-sm-6" %>
    </div><br>
    <div class="form-group row">
      <%=form.label :bio, class: "col-sm-4 col-form-label" %>
      <%=form.text_area :bio, class: "col-sm-8" %>
    </div><br>
    <div class="form-group row">
      <%=form.label :location, class: "col-sm-4 col-form-label" %>
      <%=form.text_field :location, class: "col-sm-6" %>
    </div><br>
    <div class="form-group row">
      <%= form.label :avatar, class: "col-sm-4 col-form-label" %>
      <%= form.file_field :avatar, class: "col-sm-8" %>
    </div><br>
    <div class="form-group row">
    <div class="form-check">
    Are you an artist?
      <%= form.label 'Yes', class: "custom-control custom-radio custom-control-inline"%>
      <%= form.radio_button :is_artist, true, class: "radio" %>
      <%= form.label 'No', class: "custom-control custom-radio custom-control-inline" %>
      <%= form.radio_button :is_artist, false, class: "radio" %>
  </div>
</div>
<br>
<br>
<div class="form-group row">
  <div class="col-sm-10">
      <%= form.submit %>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/profiles/edit.html.erb
<%= render 'form' %>

app/views/profiles/new.html.erb
<%= render 'form' %>

app/views/profiles/show.html.erb
<div class="rocio">
<h1 id="profileNickname"><%= @profile.nickname + "\'s profile"%></h1><br/><br/>
  <img id="imageAva"  <%= image_tag (@profile.avatar.attached?) ? @profile.avatar : "https://randomuser.me/api/portraits/med/lego/1.jpg"  %><br/><br/><br/><br/>
  <div class="tableProfile">
  <table class="table">
    <thead>
      <tr>
        <th><h5>Artist</h5></th>
        <th><h5>Location</h5></th>
      </tr>
      <tbody>
        <tr>
          <td><%= @profile.nickname %></td>
          <td><%= @profile.location %></td>
        </tr>
      </tbody>
    </table>
    <table class="table">
      <thead>
        <tr>
          <th><h5>Bio</h5></th>
        </tr>
        <tbody>
          <tr>
            <td><%= @profile.bio %></td>
          </tr>
        </tbody>
      </table>
      <table class="table">
        <thead>
          <tr>
            <th><h5>Profile Type</h5></th>
            <th><h5>Contact</h5>
          </tr>
          <tbody>
            <tr>
              <td><% if @profile.is_artist == true %>
                     <%= "Artist" %>
                  <% else %>
                     <%= "User" %>
                  <% end %>
              </td>
              <td><%= @profile.email %></td>
            </tr>
          </tbody>
        </table>
        </div>
  <% if @profile == current_user.profile %>
    <%= button_to "Edit Profile", edit_profile_path(current_user.profile), method: :get %>
  <% elsif @profile.is_artist? %>
    <%= button_to 'Back to Artists', artists_path, method: :get %>
  <% else %>
    <%= button_to 'Back to Users', users_path, method: :get %>
  <% end %>
</div>