config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  post 'home/search', to: 'home#search'
  devise_for :users
  resources :users, :only => [:index, :show]
  resources :profiles, only: [:new, :create, :show, :edit, :update]

  resources :artists, only: [:index]

  get 'about' => 'about#index'

  patch 'listings/:listing_id/biddings/:id/approve' => 'biddings#approve'
  patch 'listings/:listing_id/biddings/:id/deny' => 'biddings#deny'

  resources :listings do
    resources :biddings
  end

  resources :charges, only: [:new, :create]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/listing.rb
class Listing < ApplicationRecord
  include Rails.application.routes.url_helpers
  before_save { |listing| listing.city = listing.city.downcase }

  belongs_to :user

  has_one :profile, through: :user

  has_many :biddings

  has_many_attached :images

  validates :title, presence: true
  validates :description, presence: true
  validates :address, :city, :state, :length, :height, :due_date, :budget, presence: true

  scope :with_unviewed_biddings, -> { joins(:biddings).where(biddings: { viewed: false }).distinct }
  scope :search,    ->  (city){ where("city LIKE ?", "%#{city}%") }

  delegate :name, to: :profile, prefix: true

  def as_json(options={})
    {
      id:             id,
      title:          title,
      description:    description,
      address:        address,
      city:           city,
      state:          state,
      length:         length,
      height:         height,
      budget:         budget,
      due_date:       due_date&.strftime('%-m/%-d/%y'),
      location:       "/listings/#{id}",
      images:         images.map{ |image| rails_blob_url(image) }
    }
  end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: [:show]



   def create
     @listing = Listing.new(listing_params)
     @listing.user = current_user
     if @listing.save
       redirect_to root_path, notice: "Success! Space Pending Beautification!"
     else
       redirect_to root_path, alert: @listing.errors.full_messages.to_sentence
     end
   end

   def new
     @listing = Listing.new
   end

   def index
     respond_to do |format|
       format.html do
         @listing = Listing.new
       end
       format.json do
         listings    = (params[:city]) ? Listing.search(params[:city]) : Listing.all
         page        = (params[:page] || 1).to_i
         per_page    = 5
         total_pages = (listings.count.to_f / per_page).ceil
         total_pages = 1 if total_pages.zero?
         @listings   = listings.paginate(page: page, per_page: per_page)
         render json: { listings: @listings, page: page, totalPages: total_pages }
       end
     end
   end


  def show
    @biddings = @listing.biddings
    @biddings.update_all(viewed: true) if current_user == @listing.user
    @biddings.where(user: current_user).update_all(viewed_by_bidder: true)
    @my_bids = @biddings.select{|b| b.user == current_user}
  end



  private

  def set_listing
    @listing = Listing.find(params[:id])
  end

  def listing_params
    params.require(:listing).permit(:title, :description, :length, :city, :state, :tags, :height, :due_date, :budget, :address, images: [])
  end
end

app/views/listings/index.html.erb
<h1>All Listings</h1>

<div>
  <% Listing.all.each do |l| %>
  <%= link_to l.title,l %> <br />
  <% end %>
</div>

<br/>

<%= link_to 'Create a Listing!', new_listing_path %>

app/views/listings/new.html.erb
<div id="test">
<%= form_with(model: @listing, local: true) do |form| %>
<div id="beautify">
  <h3>Beautify My Location</h3>
</div>
  <div class="form control">
    <div class="form-group">
      <%= form.label "Listing Title"%>
      <%= form.text_field :title,
            class: "form-control col-lg-10" %>
    </div>
    <div class="form-group">
      <%= form.label "Description of project"%>
      <%= form.text_field :description,
            class: "form-control col-lg-10" %>
    </div>
    <div class="form-group">
      <%= form.label :address %>
      <%= form.text_field :address, placeholder: "123 Main Street",
            class: "form-control col-lg-10" %>
    </div>
    <div class="form-group">
      <%= form.label :city%>
      <%= form.text_field :city,
            class: "form-control col-lg-10"%>
    </div>
    <div class="form-group">
      <%= form.label "State"%>
      <%= form.text_field :state, placeholder: "(Ex: FL, or Florida)",
            class: "form-control col-lg-10"%>
    </div>
    <div class="form-group">
      <%= form.label "Tags" %>
      <%= form.text_field :tags, placeholder: "(Ex: warehouse, wall, mural, etc)",
            class: "form-control col-lg-10"%>
    </div>
    <div class="form-group">
      <%= form.label "Height (in feet)" %>
      <%= form.text_field :height,
            class: "form-control col-lg-10"%>
    </div>
    <div class="form-group">
      <%= form.label "Length (in feet)"%>
      <%= form.text_field :length,
            class: "form-control col-lg-10"%>
    </div>
    <div class="form-group">
          <%= form.label "Preferred Start Date" %>
          <%= form.date_field :due_date,
                class: "form-control col-lg-10" %>
    </div>
    <div class="form-group">
      <%= form.label "Allocated Budget" %>
      <%= form.text_field :budget, placeholder: "$",
              class: "form-control col-lg-10"%>
    </div>
    <div class="form-group">
      <%= form.label :images %>
      <%= form.file_field :images, multiple: true%>
    </div>
    <div class="actions">
      <%= form.submit :class => 'submit' %>
    </div>
    </div>
</div>
<% end %>

app/views/listings/show.html.erb
<div class= "listingpage">
  <p class="notice"><%= notice %></p>
  <div class="listingtitle">
  <h1><%= @listing.title %></h1>
  </div>
  <br>
  <div class="listingpagemain">
    <div class="carousel">
      <%= react_component 'ListingCarousel', props: { listing_images: @listing.images.map{ |image| url_for(image) } } %>
      <h5>Dimensions:</h5>
      <table class="table">
      <thead>
        <tr>
          <th><h5>Length</h5></th>
          <th><h5>Height</h5></th>
        </tr>
        <tbody>
          <tr>
            <td> <%= @listing.length %>ft</td>
            <td> <%= @listing.height %>ft</td>
          </tr>
        </tbody>
        </table>
    </div>
    <div class="listinginfo">
      <table class="table">
        <thead>
          <tr>
            <th><h5>Owner</h5></th>
            <th><h5>Description</h5></th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><h5><%= button_to @listing.profile.nickname, profile_path(@listing.user_id), method: :get%></h5></td>
            <td><h6><%= @listing.description %></h6></td>
          </tr>
        </tbody>
      </table>
        <table class="table">
          <thead>
            <tr>
              <th><h5>Address</h5></th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td id="addressRow"><%= @listing.address %></td>
            </tr>
          </tbody>
        </table>
        <table class="table">
          <thead>
            <tr>
              <th><h5>City</h5></th>
              <th><h5>State</h5></th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td><%= @listing.city %></td>
              <td><%= @listing.state %></td>
            </tr>
          </tbody>
        </table>
        <table class="table">
          <thead>
            <tr>
              <th><h5>Due Date</h5></th>
              <th><h5>Budget</h5></th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td><%= @listing.due_date %></td>
              <td>$<%= @listing.budget %>.00</td>
            </tr>
          </tbody>
        </table>
    </div>
  </div>
  <br>
  <div class= "offertable">
   <h4>Beautification Offers</h4>
   <% if current_user!= @listing.user && !current_user.has_made_offer?(@listing) %>
     <%= button_to 'Make an offer!', new_listing_bidding_path(@listing), method: :get %> <br/>
   <% end %>
    <% if current_user === @listing.user && @biddings.present? %>
   <% @biddings.each do |bid| %>
      <table id="biddingstable" class= "table table-bordered" >
        <thead>
          <tr>
            <% if current_user == @listing.user %>
              <th>Offer by</th>
              <th>Message</th>
            <% end %>
            <% if bid.apprv_deny %>
              <th>Status</th>
              <th>Payment</th>
            <% elsif bid.apprv_deny == nil %>
              <th>Approve</th>
              <th>Deny</th>
            <% else %>
              <th>Status</th>
            <% end %>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><% if bid.user.profile.try(:any?) %>
                <%= bid.user.profile.name %>
                <% else %>
                <%= bid.user.email %>
                <% end %>
            </td>
            <td><%= bid.body%></td>
            <% if bid.apprv_deny %>
              <td>Accepted</td>
              <td>
                <%= form_tag charges_path do %>
                  <div id="box" style="text-align:center;">
                    <article>
                      <%= hidden_field_tag 'amount', @listing.budget %>
                    </article>
                    <script
                      src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                      data-zip-code="true"
                      data-key="pk_test_iMWzgJ8asjYKU7Jgjs6d1op2"
                      data-amount= "<%= @listing.budget %>"
                      data-name="Beautify"
                      data-image="https://stripe.com/img/documentation/checkout/marketplace.png"
                      data-locale="auto">
                    </script>
                    <% end %>
                  </div>
                </td>
            <% elsif bid.apprv_deny == nil %>
              <td><%= button_to 'Approve', "/listings/#{@listing.id}/biddings/#{bid.id}/approve", id: 'approve-btn', method: :patch,  'data-disable-with' => 'Submiting'   %> </td>
              <td><%= button_to 'Deny', "/listings/#{@listing.id}/biddings/#{bid.id}/deny", method: :patch,  'data-disable-with' => 'Submiting'   %></td>
            <% else %>
              <td> Rejected! </td>
            <% end %>
          </tr>
        </tbody>
      </table>
        <% end %>
    <% else current_user != @listing.user && current_user.has_made_offer?(@listing) %>
    <% @my_bids.each do |bid| %>
      <table id="biddingstable">
        <thead>
          <tr>
            <th>Offer</th>
            <th>Message</th>
            <th>Status</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><% if bid.user.profile.try(:any?) %>
                <%= bid.user.profile.name %>
                <% else %>
                <%= bid.user.email %>
                <% end %>
            </td>
            <td><%= bid.body%></td>
            <td><% if bid.apprv_deny %>
                  Accepted!
                <% elsif bid.apprv_deny.nil? %>
                  Pending
                <% else %>
                  Rejected
                <% end %>
            </td>
        </tbody>
      </table>
      <% end %>
    <% end %>