config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  post 'home/search', to: 'home#search'
  devise_for :users
  resources :users, :only => [:index, :show]
  resources :profiles, only: [:new, :create, :show, :edit, :update]

  resources :artists, only: [:index]

  get 'about' => 'about#index'

  patch 'listings/:listing_id/biddings/:id/approve' => 'biddings#approve'
  patch 'listings/:listing_id/biddings/:id/deny' => 'biddings#deny'

  resources :listings do
    resources :biddings
  end

  resources :charges, only: [:new, :create]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/bidding.rb
class Bidding < ApplicationRecord
  belongs_to :listing
  belongs_to :user
  # has_one :user, through: :listing

  has_many_attached :images

  validates :title, presence: true
  validates :body, presence: true

  scope :approved_or_denied_but_not_viewed_by_bidder, -> {
    where(apprv_deny: [true, false], viewed_by_bidder: false)
  }

  def bid_id
    user = User.find(self.user_id)
    return user.id
  end

end

app/controllers/biddings_controller.rb
class BiddingsController < ApplicationController
  before_action :set_bidding, only: [:approve, :deny]
  def new
    @bidding = listing.biddings.new
  end


  def index
  end

  def show
  end

  def create

    @bidding = listing.biddings.new(bidding_params)
    @bidding.user_id = current_user.id

    if @bidding.save
      redirect_to root_path, notice: "offer made"
    else
      redirect_to root_path, alert: @bidding.errors.full_messages.to_sentence
    end
  end

  def approve
    @bidding.update(apprv_deny: true)
    redirect_to @bidding.listing, notice: "Bidding Approved"
  end

  def deny
    @bidding.update(apprv_deny: false)
    redirect_to @bidding.listing, notice: "Bidding Denied"
  end

  private

  def set_bidding
    @bidding = Bidding.find(params[:id])
  end

  def bidding_params
    params.require(:bidding).permit(:title, :body, :offer, images: [])
  end

  def listing
    Listing.find(params[:listing_id])
  end
end

app/views/biddings/new.html.erb
<div class="eduardo">
<%= form_for @bidding, url: listing_biddings_path(listing_id: @bidding.listing_id) do |form| %>
  <div class="form-group">
    <%= form.label "Subject:" %> <br>
    <%= form.text_field :title, class: "col-sm-6"  %>
  </div>
  <div>
    <%= form.label "Description:" %> <br>
    <%= form.text_area :body, class: "col-sm-6" %>
  </div>
  <div class="form-group">
    <%= form.label "Upload images:" %> <br>
    <%= form.file_field :images, multiple: true %>
    <%= form.label "Budget: $" %>
    <%= Listing.find(@bidding.listing_id).budget %>
  </div>
  <div class="actions">
    <%= form.submit "Submit Offer" %>
  </div>
<% end %>
  </div>