config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  post 'home/search', to: 'home#search'
  devise_for :users
  resources :users, :only => [:index, :show]
  resources :profiles, only: [:new, :create, :show, :edit, :update]

  resources :artists, only: [:index]

  get 'about' => 'about#index'

  patch 'listings/:listing_id/biddings/:id/approve' => 'biddings#approve'
  patch 'listings/:listing_id/biddings/:id/deny' => 'biddings#deny'

  resources :listings do
    resources :biddings
  end

  resources :charges, only: [:new, :create]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FinalProjectTemplate</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'app-bundle' %>
    <link
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
      crossorigin="anonymous"
    >
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.0/animate.css"
      integrity="sha256-gVCm5mRCmW9kVgsSjQ7/5TLtXqvfCoxhdsjE6O1QLm8="
      crossorigin="anonymous"
    />
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script
      src="https://code.jquery.com/jquery-3.3.1.min.js"
      integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
      crossorigin="anonymous">
    </script>
    <script
      src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
      integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
      crossorigin="anonymous">


    </script>
  </head>
  <body>
  <nav class="navbar navbar-expand-md">
      <div class="navbar-collapse collapse w-100 order-1 order-md-0 dual-collapse2">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item  <%= 'active' if current_page?(about_path) %>">
              <%= link_to 'Beautify Me', new_listing_path, :class => "nav-link" %>
          </li>
            <li class="nav-item  <%= 'active' if current_page?(root_path) %>">
                <%= link_to 'Browse Jobs', root_path,:class => "nav-link" %>
            </li>
            <li class="nav-item <%= 'active' if current_page?(artists_path) %>">
                <%= link_to 'Browse Artists', artists_path,:class => "nav-link" %>
            </li>
        </ul>
      </div>
    <div id="logo">
    <div class="mx-auto order-0">
        <%= link_to root_path,:class => "navbar-brand" do %>
      <%= image_tag ("logo.png"), :width => "200px" %>
      <% end %>
    </div>
  </div>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".dual-collapse2">
            <span class="navbar-toggler-icon"></span>
        </button>
    <div class="navbar-collapse collapse w-100 order-3 dual-collapse2">
        <% if !user_signed_in? %>
        <ul class="navbar-nav ml-auto">
          <li class="nav-item  <%= 'active' if current_page?(listings_path) %>">
                <%= link_to 'Login', new_user_session_path,:class => "nav-link" %>
            </li>
            <li class="nav-item  <%= 'active' if current_page?(listings_path) %>">
                  <%= link_to 'Create Account', new_user_registration_path,:class => "nav-link" %>
              </li>
        </ul>
        <% end %>

        <% if user_signed_in? %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="ml-auto navbar-nav">
          <% if @listings_with_unviewed_biddings.any? %>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="notificationDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <% if @listings_with_unviewed_biddings.count == 1 %>
                  <%= @listings_with_unviewed_biddings.count %> new offer notification!
                <% else %>
                  <%= @listings_with_unviewed_biddings.count %> new offer notifications!
                <%end %>
              </a>
              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                <% @listings_with_unviewed_biddings.each do |listing| %>
                  <%= link_to listing.title, listing, class: "dropdown-item" %>
                <% end %>
              </div>
            </li>
          <% end %>
          <% if @approved_or_denied_biddings_unviewed.any? %>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="notificationDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <% if @approved_or_denied_biddings_unviewed.count == 1 %>
               <%= @approved_or_denied_biddings_unviewed.count %> new notification!
               <% else %>
                <%= @approved_or_denied_biddings_unviewed.count %> new notifications!
                <% end %>
              </a>
              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                <% @approved_or_denied_biddings_unviewed.each do |bidding| %>
                  <%= link_to bidding.listing.title, bidding.listing, class: "dropdown-item" %>
                <% end %>
              </div>
            </li>
          <% end %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <% if current_user.profile %>
                <%= image_tag (current_user.profile.avatar.attached?) ? current_user.profile.avatar : "https://randomuser.me/api/portraits/med/lego/1.jpg", id: "ava_id" %>
              <% else %>
                <%= current_user.email %>
              <% end %>
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
              <%= link_to "Account", edit_user_registration_path, class: "dropdown-item" %>
              <div class="dropdown-divider"></div>
              <% if current_user.profile %>
                <%= link_to "View Profile", profile_path(current_user.profile), class: "dropdown-item" %>
              <% elsif current_user.profile.nil? %>
                <%= link_to "Create your profile", new_profile_path, class: "dropdown-item" %>
              <% else %>
                <%= link_to "Sign up!", new_user_registration, class: "dropdown-item" %>
              <% end %>
              <div class="dropdown-divider"></div>
              <%= link_to "Sign Out", destroy_user_session_path,
                  method: :delete,
                  class: "dropdown-item" %>
              </div>
            </li>
          </ul>
        <% end %>
    </div>
</nav>
<div id="mn">
  <div id="cs">
    <p class="notice" style="color:green;"><%= notice %></p>
    <p class="notice" style="color:red;"><%= alert %></p>
    <%= yield %>
    </div>
    </div>
    <footer class="transparent text-black mt-5">
    <div class="container-fluid">
        <div class="row">
            <div class="col">
                <h5></h5></div>
            <div class="col"></div>
            <div class="col"></div>
            <div class="col"></div>
        </div>
        <div class="row">
            <div class="col">beautify <span class="small"><br>
            Located: <br>
            549 NW 28th Street<br>
            Miami, FL 33127</span></div>
            <div class="col"></div>
            <div class="imgFooter">
              <%= link_to "https://www.facebook.com/mikeymagoo" do %>
                <%= image_tag ("facebook.png"), :width => "50px", :height => "50px" %>
              <% end %>
              <%= link_to "https://www.instagram.com/mike__tips" do %>
                <%= image_tag ("ig.png"), :width => "50px", :height => "50px" %>
              <% end %>
              <%= link_to "https://twitter.com/mikethetomato1" do %>
                <%= image_tag ("twit.png"), :width => "50px", :height => "50px"%>
              <% end %>
            </div>
            <div class="col"></div>
            <div class="footer-copyright">©2019 beautify. All rights reserved.</div>
        </div>
    </div>
</footer>
  </body>
</html>